format = """\
[î‚¶](#9A348E)\
$username\
[î‚°](bg:#DA627D fg:#9A348E)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$all\
$cmd_duration\
[î‚°](fg:#86BBD8 bg:#33658A)\
$battery\
$time\
$character"""

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[îŠ† $user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜"
"Downloads" = "ï€™"
"Music" = "ğŸœ"
"Pictures" = "ï‘†"
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ï˜"
style = "bg:#FCA17D"
format = '[[ $symbol $branch(:$remote_branch) ](bg:#FCA17D)]($style)'

[git_status]
style = "bg:#FCA17D"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"
format = '[[$all_status$ahead_behind ](bg:#FCA17D)]($style)'


[aws]
symbol = "îŒ½ "
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[conda]
symbol = "ï„Œ"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[dart]
symbol = "î˜"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[c]
symbol = "î˜"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#06969A"
format = '[[ $symbol $context](bg:#86BBD8)]($style) $path'

[elixir]
symbol = "î‰µ"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[elm]
symbol = "î˜¬"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[haskell]
symbol = "Î»"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[java]
symbol = "î‰–"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[julia]
symbol = "î˜¤"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[nim]
symbol = "ïš¤"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[nix_shell]
symbol = "ï‹œ"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[nodejs]
symbol = "î‰"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[perl]
symbol = "î©"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[python]
symbol = "î˜†"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[ruby]
symbol = "îˆ¾"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[swift]
symbol = "ï¯£"
style = "bg:#86BBD8"
format = '[[ $symbol ($version )](bg:#86BBD8)]($style)'

[package]
symbol = "ï£–"
disabled = true


[cmd_duration]
min_time = 1
format = "[$duration ](bg:#86BBD8)"
disabled = true

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
unknown_symbol = "ï•¼ "
empty_symbol = "ï– "
format = "[ $symbol$percentage ](bg:#33658A)"
disabled = false

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 101
style = "bold green"

# Prompt: optional param 1
[time]
disabled = true
time_format = "%R"
style = "bg:#06969A"
format = '[î‚°](fg:#33658A bg:#06969A)[ ï•ª $time ]($style)'

# Last param in the first line/row
# fg:#06969A if time enabled
[character]
success_symbol = "[îƒ€ ](fg:#33658A)"
error_symbol = "[îƒ† ](fg:#33658A)"
